name = "ai-appbuilder"
main = "worker/index.ts"
compatibility_date = "2025-08-10"
compatibility_flags = ["nodejs_compat"]
workers_dev = false
preview_urls = false

[version_metadata]
binding = "CF_VERSION_METADATA"

[assets]
directory = "dist"
not_found_handling = "single-page-application"
binding = "ASSETS"

[observability]
enabled = true
head_sampling_rate = 1

[ai]
binding = "AI"
remote = true

[images]
binding = "IMAGES"

[[dispatch_namespaces]]
binding = "DISPATCHER"
namespace = "vibesdk-default-namespace"
remote = true

[[d1_databases]]
binding = "DB"
database_name = "aibuilder-db"
database_id = "b8b5ea6b-8a9c-4b19-a191-129cfd69d53f"
migrations_dir = "migrations"
remote = true

[durable_objects]
bindings = [
  { class_name = "CodeGeneratorAgent", name = "CodeGenObject" },
  { class_name = "UserAppSandboxService", name = "Sandbox" },
  { class_name = "DORateLimitStore", name = "DORateLimitStore" }
]

[[r2_buckets]]
binding = "TEMPLATES_BUCKET"
bucket_name = "vibesdk-templates"
remote = true

[[kv_namespaces]]
binding = "VibecoderStore"
id = "7382e9c21d8c4ae69f9395c6e7acaf93"
remote = true

[[migrations]]
tag = "v1"
new_sqlite_classes = ["CodeGeneratorAgent", "UserAppSandboxService"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["DORateLimitStore"]

[[routes]]
pattern = "build.cloudflare.dev"
custom_domain = true

[[routes]]
pattern = "*build-preview.cloudflare.dev/*"
custom_domain = false
zone_id = "db01fac4261b2604aacad8410443a3e2"

[vars]
TEMPLATES_REPOSITORY = "https://github.com/cloudflare/vibesdk-templates"
ALLOWED_EMAIL = "*"
DISPATCH_NAMESPACE = "vibesdk-default-namespace"
ENABLE_READ_REPLICAS = "true"
CLOUDFLARE_AI_GATEWAY = "vibesdk-gateway"
CUSTOM_DOMAIN = "builder.1mappstories.com"
MAX_SANDBOX_INSTANCES = "10"
SANDBOX_INSTANCE_TYPE = "standard"
